version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - LOG_SHORT_TIME=true
      - LOG_FIELD_BLACKLIST=caller,sequence_number
      - LOG_LEVEL=debug
      - POSTGRES_URL=postgres://ijci:ijci@postgres/ijci?sslmode=disable
      - AMQP_EXCHANGE=ijci
      - AMQP_ROUTING_KEY=key
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - 5000:5000

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - LOG_SHORT_TIME=true
      - LOG_FIELD_BLACKLIST=caller,sequence_number
      - LOG_LEVEL=debug
      - AMQP_CONSUMER_TAG=ctag
      - AMQP_EXCHANGE=ijci
      - AMQP_ROUTING_KEY=key
      - AMQP_QUEUE_NAME=build-requests
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    volumes:
      - ./repos:/repos
      - /var/run/docker.sock:/var/run/docker.sock

  # External Services

  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=ijci
      - POSTGRES_USER=ijci
      - POSTGRES_PASSWORD=ijci
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
